### ISSUE TITLE
Home Navigation/UI Issues

### ISSUE THREAD

**Issue by GunnarTheCroc** [423s24/Group_5#1]
When I'm logged in and on the dashboard, clicking the HRDC logo in the top left corner of the webpage takes me back to the page where it asks me to login. However, since I'm still logged in, clicking the login button skips the login screen and just loads the dashboard again. This is confusing design, as I don't know if I'm logged in or not when I get sent to that screen, and I don't expect clicking the logo to send me back to that screen. A solution for this could be have the logo point to the dashboard, remove the dashboard button as it's redundant, and just have "sign out" point back to the sign in page and sign you out like it does already.

**Comment by mykados** [comment]
Got fixed in recent patches
